### ISSUE TITLE
How do I use this

### ISSUE THREAD

**Issue by SuperMario20** [SlawekNowy/vsif2vcd#1]
Idk how to compile it. What do I use?

**Comment by MrSoup678** [comment]
Cmake and vcpkg. Hovever this program is very incomplete. I'll look into this when I finish this.

**Comment by SuperMario20** [comment]
Also I've noticed that games that don't have the scenes in the maps and are only in the code (TF2 etc.) will output some jumbled up vcd names when you decompile the scenes.image and error when rebuilt into scenes.image.

**Comment by SuperMario20** [comment]
trying to compile this errors at line 25 of the CMakeLists.txt where it says "find package (Bitsery CONFIG REQUIRED)"

**Comment by SuperMario20** [comment]
How do I install Bitsery?

**Comment by MrSoup678** [comment]
I use vcpkg to manage dependencies.
You can get this program [here](https://github.com/microsoft/vcpkg).

Additiionally I'm setting up CI right now to migitate those issues in a future.

**Comment by MrSoup678** [comment]
Finished the program. Just supply game directory (e.g.: hl2, episodic, ep2) where gameinfo.txt is located as an executable

**Comment by SuperMario20** [comment]
> Finished the program. Just supply game directory (e.g.: hl2, episodic, ep2) where gameinfo.txt is located as an executable

ok. Will you put a release for the project?

**Comment by Ashe-tf** [comment]
Does this works for TF2?

**Comment by SuperMario20** [comment]
I still have no clue. I've never been able to successfully compile the latest version, and the release has the same issues as the open issue that I posted a while ago because it hasn't been updated. It theoretically should work on the latest version, but only if you're able to compile it successfully.

**Comment by SuperMario20** [comment]
> Does this works for TF2?

Finally got a chance to test it out after compiling it successfully. It has **some** success, but for some reason has been unable to name all of the TF2 vcd files, only succeeding on a select few.
[https://github.com/SuperMario20/vsif2vcd/releases/tag/1.0.1](url)
