### ISSUE TITLE
problems with compiling

### ISSUE THREAD

**Issue by Jordon87** [SlawekNowy/vsif2vcd#10]
i don't know what i'm doing wrong here.

i've compiled with cmake, but each time i try to compile it keeps getting me errors about spdlog.
![image](https://github.com/SlawekNowy/vsif2vcd/assets/38020644/dbd67710-17e8-46b4-adc9-f8f2b2761656)

**Comment by Xalalau** [comment]
Change ``set(SPDLOG_FMT_EXTERNAL ON)`` to ``set(SPDLOG_FMT_EXTERNAL OFF)`` in vsif2vcd/CMakeLists.txt so spdlog can use a bundled version of the fmt library.

**Comment by Jordon87** [comment]
thanks, the code compiles well, but now there's link errors involving "fmt::v9".

**Comment by Jordon87** [comment]
thanks, the code compiles well, but now there's link errors involving "fmt::v9".
![image](https://github.com/SlawekNowy/vsif2vcd/assets/38020644/c47dc426-6fa9-44c1-96a6-0fe4e49b8c3e)
