### ISSUE TITLE
(improvement ) Scenes.image extraction without scenes in the map files

### ISSUE THREAD

**Issue by SuperMario20** [SlawekNowy/vsif2vcd#2]
I've noticed that games that don't have the scenes in the maps and are only in the code (TF2 etc.) will output some jumbled up vcd names when you decompile the scenes.image and error when rebuilt into scenes.image. Could you find a way in the future to get it working for games without scenes in the maps?

**Comment by MrSoup678** [comment]
Already found a way. In all source games there's this thing called response system. It allows to play VCD based on criteria met.

More on this [here](https://developer.valvesoftware.com/wiki/Response_System).

Scripts related in this system are in scripts/talker in any source game.

Example: [TF2 Scout's response script](https://github.com/SteamDatabase/GameTracking-TF2/blob/master/tf/tf2_misc_dir/scripts/talker/scout.txt)

Right now I'm porting this program to c++, so this needs to wait. Thanks for your concern tho.

Entrypoint for those scripts is always scripts/talker/response_rules.txt file.

**Comment by MrSoup678** [comment]
There's not much in the code actually. And in fact I handle those already. it's in hardcoded_entries.h file.

**Comment by SuperMario20** [comment]
thanks

**Comment by SuperMario20** [comment]
How's it going so far?

**Comment by MrSoup678** [comment]
Finished up scene dumping. Now it will correctly decompile via test program. Soon I'll get map parser logic implemented.
Bulk of will be in my valve-bsp-parser fork. Once done, I will add that as a submodule and extract necessary information from it.

**Comment by SuperMario20** [comment]
Cool!
